version: "3"

services:
  app:
    build: .
    environment:
      MIX_ENV: ${MIX_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app:/application
    working_dir: /application
    ports:
      - "${APP_PORT}:4000"
    depends_on:
      - "db"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  default: